# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180502_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='big',
            new_name='large',
        ),
    ]
