# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-02 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180502_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='large',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='small',
        ),
    ]
